INSERT INTO PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID, PRODUCT_CATEGORY_NAME)
    VALUES (NEXTVAL('PRODUCT_CATEGORY_SEQ'), 'T-SHIRT');

INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE, SALE, SALE_PERCENTAGE, PRODUCT_CATEGORY)
    VALUES (NEXTVAL('PRODUCT_SEQ'), 'Clean cut t-shirt', 35, 0, null, 1);